// apps/host/src/react-form.tsx
import type { ReactElement } from 'react'
import type { FormEngine } from '@formancy/core'
import { ErrorSummary, FormancyForm, FormancyProvider, OptionsSourcesProvider } from '@formancy/react'
import type { OptionsSources, SubmitOutcome } from '@formancy/react'
import { fieldLabels } from './labels.js'

/**
 * The React renderer's half of a pane: the error summary, then the form, with
 * "Save" as its submit -- the Angular pane's two parts, in its order.
 *
 * The summary is the host's to place: `FormancyForm` includes none. It focuses
 * itself when errors appear, after the engine refuses a submit and after the
 * server names a field. The layout is the document's own, as the Angular half
 * reads it.
 *
 * `sources` is `lookupSources(...)` from `@formancy/data-client`, typed here as
 * this renderer's own `OptionsSources`: this file's type check is the one that
 * fails when that stops fitting (0029).
 */
export function ReactForm({
  engine,
  sources,
  onSubmit,
}: {
  engine: FormEngine
  sources: OptionsSources
  onSubmit: (outcome: SubmitOutcome) => void
}): ReactElement {
  const layout = engine.schema().layouts?.[0]?.name
  return (
    <OptionsSourcesProvider value={sources}>
      <FormancyProvider engine={engine}>
        <ErrorSummary labels={fieldLabels(engine)} />
        <FormancyForm {...(layout === undefined ? {} : { layout })} submitLabel="Save" onSubmit={onSubmit} />
      </FormancyProvider>
    </OptionsSourcesProvider>
  )
}

// apps/host/src/angular-form.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core'
import { FormancyErrorSummary, FormancyForm, injectEngine } from '@formancy/angular'
import { HOST_SAVE } from './angular-save.js'
import { fieldLabels } from './labels.js'

/**
 * The Angular renderer's half of a pane: the error summary, then the form,
 * with "Save" as its submit. The same two parts, in the same order, as the
 * React pane, so a difference on screen is a difference of renderer.
 *
 * The summary is the host's to place -- neither renderer's form includes one
 * -- and it focuses itself when errors appear: after the engine refuses a
 * submit, and after the server names a field.
 *
 * **This file holds the component and nothing else**, for the reason in
 * angular-save.ts.
 */
@Component({
  selector: 'formancy-data-host-form',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyErrorSummary, FormancyForm],
  template: `<formancy-error-summary [labels]="labels" /><formancy-form [layout]="layout" submitLabel="Save" (submitted)="save($event)" />`,
})
export class HostAngularForm {
  private readonly engine = injectEngine()
  protected readonly layout = this.engine.schema().layouts?.[0]?.name
  protected readonly labels = fieldLabels(this.engine)
  protected readonly save = inject(HOST_SAVE)
}
